"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { serviceClient } from "@/lib/db/client";
import { currentUserId } from "@/lib/auth/owner";
import { advanceAllSequences } from "@/lib/sequences/engine";
import { SEQUENCE_STEPS } from "@/lib/sequences/steps";
import { flash } from "@/lib/flash";

const str = (v: FormDataEntryValue | null): string | null => {
  const s = String(v ?? "").trim();
  return s === "" ? null : s;
};

export async function createSequenceAction(formData: FormData) {
  const name = str(formData.get("name"));
  if (!name) return;
  const owner_id = (await currentUserId()) ?? null;
  // auto_send defaults true (zero-touch). Operator can flip on detail page.
  const auto_send = formData.get("auto_send") !== "off";
  const { data, error } = await serviceClient()
    .from("sequences")
    .insert({ name, owner_id, auto_send })
    .select("id")
    .single();
  if (error) throw error;
  await flash("success", `Sequence created: ${name}`);
  revalidatePath("/sequences");
  redirect(`/sequences/${data.id}`);
}

/** Toggle auto_send on an existing sequence. Affects emails generated by
 *  the engine from now on — drafts already sitting in /queue keep their
 *  current status. */
export async function setSequenceAutoSendAction(formData: FormData) {
  const id = String(formData.get("id"));
  const auto_send = formData.get("auto_send") === "on";
  if (!id) return;
  await serviceClient().from("sequences").update({ auto_send }).eq("id", id);
  await flash("success", auto_send ? "Auto-send ON — emails ship inside the next send window" : "Review mode — emails land in /queue for approval");
  revalidatePath(`/sequences/${id}`);
}

export async function setSequenceStatusAction(formData: FormData) {
  const id = String(formData.get("id"));
  const status = str(formData.get("status")) ?? "live";
  if (!["live", "paused", "complete"].includes(status)) return;
  await serviceClient().from("sequences").update({ status }).eq("id", id);
  await flash("success", `Sequence → ${status}`);
  revalidatePath(`/sequences/${id}`);
  revalidatePath("/sequences");
}

export async function deleteSequenceAction(formData: FormData) {
  const id = String(formData.get("id"));
  await serviceClient().from("sequences").delete().eq("id", id);
  await flash("success", "Sequence deleted");
  revalidatePath("/sequences");
  redirect("/sequences");
}

/** Add one or many contacts to a sequence. Each new sequence_contact starts
 *  at step 0 with started_at = now, so the cron's next tick decides what
 *  to do for them (typically creates the Day-1 LinkedIn actions). */
export async function addContactsToSequenceAction(formData: FormData) {
  const sequence_id = String(formData.get("sequence_id"));
  const contactIds = formData.getAll("contact_id").map(String).filter(Boolean);
  if (!sequence_id || contactIds.length === 0) return;
  const added_by = await currentUserId();
  const rows = contactIds.map((contact_id) => ({
    sequence_id,
    contact_id,
    current_step: 0,
    started_at: new Date().toISOString(),
    status: "active",
    added_by,
  }));
  // Upsert so re-adding a contact is a no-op rather than an error.
  const { error } = await serviceClient()
    .from("sequence_contacts")
    .upsert(rows, { onConflict: "sequence_id,contact_id", ignoreDuplicates: true });
  if (error) throw error;
  await flash("success", `Added ${contactIds.length} contact${contactIds.length === 1 ? "" : "s"}`);
  revalidatePath(`/sequences/${sequence_id}`);
}

export async function removeContactFromSequenceAction(formData: FormData) {
  const sequence_id = String(formData.get("sequence_id"));
  const contact_id = String(formData.get("contact_id"));
  if (!sequence_id || !contact_id) return;
  const db = serviceClient();
  await db.from("sequence_contacts").delete().eq("sequence_id", sequence_id).eq("contact_id", contact_id);
  // Also clear any pending actions for this contact in this sequence.
  await db.from("sequence_actions").delete()
    .eq("sequence_id", sequence_id).eq("contact_id", contact_id).eq("status", "pending");
  await flash("success", "Contact removed from sequence");
  revalidatePath(`/sequences/${sequence_id}`);
}

/** Log a sequence-action outcome into the contact's events timeline so
 *  every completed step shows up alongside emails / meetings / notes on
 *  the contact page. */
async function logSequenceEvent(opts: {
  contact_id: string;
  sequence_id: string;
  step_index: number;
  kind: string;
  outcome: "done" | "skipped";
}) {
  const step = SEQUENCE_STEPS[opts.step_index];
  const label = step?.label ?? opts.kind;
  const db = serviceClient();
  // Pull org from the contact to fill events.organisation_id too.
  const { data: c } = await db.from("contacts").select("organisation_id").eq("id", opts.contact_id).maybeSingle();
  await db.from("events").insert({
    contact_id: opts.contact_id,
    organisation_id: (c?.organisation_id as string | null) ?? null,
    type: "crm_change",
    source: "sequence",
    payload: {
      message: `Sequence step ${opts.outcome}: ${label}`,
      sequence_id: opts.sequence_id,
      step_index: opts.step_index,
      step_kind: opts.kind,
      outcome: opts.outcome,
    },
  });
}

/** Mark a single action done. Advances current_step on the parent
 *  sequence_contact; the cron's next tick handles the next step.
 *  Also logs an event on the contact's timeline. */
export async function markActionDoneAction(formData: FormData) {
  const id = String(formData.get("id"));
  if (!id) return;
  const db = serviceClient();
  const me = await currentUserId();
  const { data: action } = await db
    .from("sequence_actions")
    .select("sequence_id, contact_id, step_index, kind")
    .eq("id", id)
    .maybeSingle();
  if (!action) return;
  await db.from("sequence_actions").update({
    status: "done",
    completed_at: new Date().toISOString(),
    completed_by: me,
  }).eq("id", id);
  await db.from("sequence_contacts").update({
    current_step: (action.step_index as number) + 1,
    last_advanced_at: new Date().toISOString(),
  }).eq("sequence_id", action.sequence_id).eq("contact_id", action.contact_id);
  await logSequenceEvent({
    contact_id: action.contact_id as string,
    sequence_id: action.sequence_id as string,
    step_index: action.step_index as number,
    kind: action.kind as string,
    outcome: "done",
  });
  await flash("success", "Action marked done");
  revalidatePath(`/sequences/${action.sequence_id}`);
  revalidatePath(`/contacts/${action.contact_id}`);
}

export async function skipActionAction(formData: FormData) {
  const id = String(formData.get("id"));
  if (!id) return;
  const db = serviceClient();
  const me = await currentUserId();
  const { data: action } = await db
    .from("sequence_actions")
    .select("sequence_id, contact_id, step_index, kind")
    .eq("id", id)
    .maybeSingle();
  if (!action) return;
  await db.from("sequence_actions").update({
    status: "skipped",
    completed_at: new Date().toISOString(),
    completed_by: me,
  }).eq("id", id);
  await db.from("sequence_contacts").update({
    current_step: (action.step_index as number) + 1,
    last_advanced_at: new Date().toISOString(),
  }).eq("sequence_id", action.sequence_id).eq("contact_id", action.contact_id);
  await logSequenceEvent({
    contact_id: action.contact_id as string,
    sequence_id: action.sequence_id as string,
    step_index: action.step_index as number,
    kind: action.kind as string,
    outcome: "skipped",
  });
  await flash("success", "Action skipped");
  revalidatePath(`/sequences/${action.sequence_id}`);
  revalidatePath(`/contacts/${action.contact_id}`);
}

/** Persist the per-sequence theme + linked conference_id. */
export async function updateSequenceMetaAction(formData: FormData) {
  const id = String(formData.get("id"));
  if (!id) return;
  const theme = str(formData.get("theme"));
  const conference_id = str(formData.get("conference_id"));
  await serviceClient().from("sequences").update({
    theme,
    conference_id,
    updated_at: new Date().toISOString(),
  }).eq("id", id);
  await flash("success", "Sequence saved");
  revalidatePath(`/sequences/${id}`);
}

/** Manual tick — re-runs the engine on demand. Useful when the operator
 *  adds contacts mid-day and doesn't want to wait for the next cron tick. */
export async function tickSequencesAction() {
  const res = await advanceAllSequences(serviceClient());
  // Surface skipped-draft reasons up-front — silent skips ("contact has
  // no company/sector") were the #1 "why is /queue empty?" puzzle.
  const skipNote = res.draftsSkipped > 0 ? ` · ${res.draftsSkipped} SKIPPED` : "";
  const firstErr = res.errors.length > 0 ? ` — first: ${res.errors[0]}` : "";
  const level: "success" | "error" =
    res.draftsSkipped > 0 || res.errors.length > 0 ? "error" : "success";
  await flash(
    level,
    `Engine tick — ${res.considered} considered · ${res.actionsCreated} new actions · ${res.draftsQueued} drafts queued${skipNote} · ${res.contactsCompleted} completed${firstErr}`,
  );
  revalidatePath("/sequences");
}
