// Voice spec pipeline (build brief step 3).
//
//   npm run voice-spec
//
// Distils a reusable VOICE SPEC from Jim's real sent emails. The spec is the
// abstract style guide fed to every generation — NOT the raw emails (brief §7:
// "distil a voice spec, don't dump them in the prompt"). Output is committed
// markdown with no client/recipient names; the anonymisation guard backstops
// the roster.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { config } from "dotenv";
import { generateText } from "../src/lib/ai/claude";
import { checkAnonymisation } from "../src/lib/generate/anonymisation";

config({ path: ".env.local", override: true });

const CORPUS = "inputs/sent-emails/voice-corpus.md";
const OUT = "creditcanary-voice-spec.md";

const SYSTEM = `You are a voice analyst. You are given a corpus of a founder's real
sent emails (Jim Fell, CEO of Credit Canary — a UK credit-decisioning + payments
fintech). Produce a reusable VOICE SPEC in markdown that another writer or an LLM
can follow to draft outreach in his exact voice.

Cover, with concrete observations drawn from the corpus:
- Openings (how he starts, relational hooks, greetings)
- Sentence rhythm and length; paragraph structure
- How he deploys proof / specifics / numbers
- Dry asides, humour, warmth
- Framing (he shares useful/exclusive insight rather than selling)
- CTA style (soft, optionality-preserving)
- Sign-offs and signature
- Vocabulary and British conventions, contractions
- An explicit DO list and DON'T list
- Anti-patterns: the register to AVOID (formal, corporate, feature-dump)

HARD RULES:
- Abstract everything. Do NOT include any company names, person names, product
  names, or specific deal details from the corpus. Describe patterns, not
  instances. If you give an example phrase, make it generic.
- Output ONLY the markdown spec. No preamble.`;

async function main() {
  if (!existsSync(CORPUS)) {
    console.error(`Missing ${CORPUS} — drop the sent-email corpus there first.`);
    process.exit(1);
  }
  const corpus = readFileSync(CORPUS, "utf8");

  console.log("Distilling voice spec from corpus…");
  const spec = await generateText({
    system: SYSTEM,
    user: `Here is the corpus of sent emails:\n\n${corpus}`,
    effort: "high",
    maxTokens: 6000,
  });

  // Backstop: the roster must never leak into a committed artifact.
  const check = checkAnonymisation(spec);
  if (!check.clean) {
    console.error(`Voice spec contains roster names (${check.hits.join(", ")}) — not writing.`);
    process.exit(1);
  }

  const header = `<!-- Generated by scripts/voice-spec.ts from the sent-email corpus.
     Abstract style guide only (no client/recipient names). Re-run to refresh. -->\n\n`;
  writeFileSync(OUT, header + spec + "\n");
  console.log(`Wrote ${OUT} (${spec.length} chars)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
